title = "Plp Constructions"
baseURL = "http://plpconstructions.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "fr-CA"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies